(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const get=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}};
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const uid=()=> 'vm_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,9);
const now=()=>new Date().toISOString();
const today=()=>new Date().toISOString().slice(0,10);
const time=()=>new Date().toTimeString().slice(0,5);
const toast=(m)=>{ if(window.alert) alert(m); };
function users(){return get('vm_users', get('users', []));}
function saveUsers(u){set('vm_users',u);set('users',u)}
function currentUser(){let id=get('vm_user_session',null)||get('vm_portal_user',null)||get('currentUserId',null); let u=users().find(u=>u.id===id); if(u) return u; try{let emp=JSON.parse(sessionStorage.getItem('vm_employee_session')||'null'); if(emp){return {id:emp.id||emp.username,username:emp.username,fullName:emp.name||emp.fullName,role:'employee',permissions:{attendance:true},password:emp.password||emp.pin||''}}}catch(e){} return null;}
function log(action,section,details,oldData=null,newData=null){let a=get('activityLogs',[]);a.unshift({id:uid(),userId:(currentUser()||{}).id||'admin',action,section,details,oldData,newData,deviceInfo:navigator.userAgent,createdAt:now()});set('activityLogs',a.slice(0,1000));}
function notify(to,type,title,message,link=''){let arr=get('notifications',[]);arr.unshift({id:uid(),to,type,title,message,link,read:false,createdAt:now()});set('notifications',arr);}
function b64(buf){return btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64(s){s=s.replace(/-/g,'+').replace(/_/g,'/'); const pad='='.repeat((4-s.length%4)%4); return Uint8Array.from(atob(s+pad),c=>c.charCodeAt(0));}
async function getGPS(){return new Promise(res=>{if(!navigator.geolocation) return res(null); navigator.geolocation.getCurrentPosition(p=>res({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,createdAt:now()}),()=>res(null),{enableHighAccuracy:true,timeout:9000,maximumAge:5000});});}
function distanceMeters(a,b,c,d){const R=6371000,rad=x=>x*Math.PI/180; const x=rad(c-a), y=rad(d-b); const h=Math.sin(x/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(y/2)**2; return 2*R*Math.asin(Math.sqrt(h));}
function deviceInfo(){return {ua:navigator.userAgent,platform:navigator.platform,language:navigator.language,createdAt:now()};}
function findEmp(user){let emps=get('employees',[]), e=emps.find(x=>x.userId===user.id||x.id===user.employeeId); if(!e){e={id:uid(),userId:user.id,employeeNumber:user.employeeNumber||('EMP-'+String(emps.length+1).padStart(3,'0')),fullName:user.fullName||user.name||user.username,department:user.department||'',jobTitle:user.jobTitle||'',salary:+(user.salary||0),workHours:{start:'09:00',end:'17:00'},status:'active',allowOutside:false}; emps.push(e); set('employees',emps);} return e;}
function hours(a,b){if(!a||!b)return 0;let A=a.split(':').map(Number),B=b.split(':').map(Number);return Math.max(0,((B[0]*60+B[1])-(A[0]*60+A[1]))/60)}
async function registerPasskey(user){
 if(!window.PublicKeyCredential || !navigator.credentials || location.protocol!=='https:' && location.hostname!=='localhost') throw new Error('البصمة تحتاج HTTPS أو localhost');
 const challenge=crypto.getRandomValues(new Uint8Array(32));
 const userId=crypto.getRandomValues(new Uint8Array(16));
 const cred=await navigator.credentials.create({publicKey:{challenge,rp:{name:'VISION MEDIA'},user:{id:userId,name:user.username||user.email||user.id,displayName:user.fullName||user.name||user.username||'VISION MEDIA User'},pubKeyCredParams:[{type:'public-key',alg:-7},{type:'public-key',alg:-257}],authenticatorSelection:{userVerification:'preferred',residentKey:'preferred'},timeout:60000,attestation:'none'}});
 const item={id:uid(),userId:user.id,credentialId:b64(cred.rawId),type:cred.type,status:'active',deviceInfo:deviceInfo(),createdAt:now(),lastUsedAt:null};
 let arr=get('biometricCredentials',[]).filter(x=>x.userId!==user.id); arr.push(item); set('biometricCredentials',arr); log('register','biometric','تفعيل بصمة / Face ID',null,item); notify('admin','biometric','تفعيل بصمة جديد','تم تفعيل بصمة لمستخدم: '+(user.fullName||user.username)); return item;
}
async function verifyPasskey(user){
 const rec=get('biometricCredentials',[]).find(x=>x.userId===user.id && x.status==='active'); if(!rec) throw new Error('لا توجد بصمة مفعلة');
 if(!window.PublicKeyCredential || !navigator.credentials || location.protocol!=='https:' && location.hostname!=='localhost') throw new Error('البصمة تحتاج HTTPS أو localhost');
 const assertion=await navigator.credentials.get({publicKey:{challenge:crypto.getRandomValues(new Uint8Array(32)),allowCredentials:[{type:'public-key',id:unb64(rec.credentialId)}],userVerification:'preferred',timeout:60000}});
 let arr=get('biometricCredentials',[]); let r=arr.find(x=>x.id===rec.id); if(r) r.lastUsedAt=now(); set('biometricCredentials',arr); return assertion;
}
async function ensureBaseLocation(user){let locs=get('employeeLocations',[]), old=locs.find(x=>x.userId===user.id && x.status==='active'); if(old) return old; let gps=await getGPS(); if(!gps) return null; let item={id:uid(),userId:user.id,employeeId:(findEmp(user)||{}).id,lat:gps.lat,lng:gps.lng,accuracy:gps.accuracy,address:'تم الحفظ من GPS',region:'غير محدد',deviceInfo:deviceInfo(),status:'active',createdAt:now()}; locs.push(item); set('employeeLocations',locs); log('create','location','تسجيل الموقع الأساسي',null,item); notify('admin','location','موقع أساسي جديد','تم حفظ موقع أساسي للمستخدم: '+(user.fullName||user.username)); return item;}
function createRequest(user,type,reason,newData){let old={}; if(type==='biometric') old=get('biometricCredentials',[]).find(x=>x.userId===user.id)||{}; if(type==='location') old=get('employeeLocations',[]).find(x=>x.userId===user.id&&x.status==='active')||{}; if(type==='device') old=(old.deviceInfo||deviceInfo()); let arr=get('reactivationRequests',[]); let req={id:uid(),userId:user.id,employeeId:(findEmp(user)||{}).id,name:user.fullName||user.name||user.username,type,reason,oldData:old,newData,status:'pending',adminMessage:'',createdAt:now()}; arr.unshift(req); set('reactivationRequests',arr); log('request','reactivation','طلب إعادة تفعيل '+type,old,newData); notify('admin','reactivation','طلب إعادة تفعيل',`${req.name} أرسل طلب ${type}`); return req;}
function getBranch(){let branches=get('branches',[]); return branches[0]||get('attendanceSettings',null)||{name:'الفرع الرئيسي',lat:null,lng:null,radius:250,allowOutside:false};}
function inScope(gps,user){let b=getBranch(), emp=findEmp(user); if(!gps||!b||!b.lat||!b.lng) return {ok:true,meters:null,branch:b}; let meters=distanceMeters(+b.lat,+b.lng,+gps.lat,+gps.lng); let ok=meters <= (+b.radius||250) || b.allowOutside===true || b.allowOutside==='true' || emp.allowOutside; return {ok,meters,branch:b};}
async function punch(type){let user=currentUser(); if(!user) return toast('يجب تسجيل الدخول'); let emp=findEmp(user); let method='PIN احتياطي'; try{await verifyPasskey(user); method='بصمة / Face ID'}catch(e){let pin=prompt('الجهاز لا يدعم البصمة أو لم يتم التحقق. أدخل PIN / كلمة المرور الاحتياطية'); if(!pin || String(pin)!==String(user.pin||user.password||user.passwordHash||'')) return toast('فشل التحقق');}
 let gps=await getGPS(); let scope=inScope(gps,user); if(!scope.ok) return toast('أنت خارج نطاق الدوام'); let all=get('attendance',[]), d=today(); let r=all.find(x=>x.employeeId===emp.id && x.date===d); if(!r){r={id:uid(),employeeId:emp.id,employeeName:emp.fullName,employeeNumber:emp.employeeNumber,department:emp.department,date:d,createdAt:now()}; all.push(r);} if(type==='in'){ if(r.checkIn && !emp.allowMultipleCheckIn) return toast('تم تسجيل الحضور اليوم بالفعل'); r.checkIn=time(); r.checkInLocation=gps; r.attendanceStatus='حاضر'; } else { r.checkOut=time(); r.checkOutLocation=gps; } r.deviceInfo=deviceInfo(); r.verificationMethod=method; r.totalHours=hours(r.checkIn,r.checkOut); let late=hours((emp.workHours||{}).start||'09:00',r.checkIn||'09:00'); r.lateHours=+(Math.max(0,late).toFixed(2)); r.overtimeHours=+(Math.max(0,hours((emp.workHours||{}).end||'17:00',r.checkOut||'17:00')).toFixed(2)); set('attendance',all); log(type==='in'?'checkIn':'checkOut','attendance',`${emp.fullName} ${type==='in'?'سجل حضور':'سجل انصراف'}`,null,r); notify('admin','attendance',type==='in'?'تسجيل حضور':'تسجيل انصراف',`${emp.fullName} - ${r.date} ${type==='in'?r.checkIn:r.checkOut}`); notify(user.id,'attendance','تم تحديث الحضور',type==='in'?'تم تسجيل حضورك بنجاح':'تم تسجيل انصرافك بنجاح'); renderPortalWidget(); toast(type==='in'?'تم تسجيل الحضور':'تم تسجيل الانصراف');}
function renderPortalWidget(){let mount=$('#vmEmployeeAttendanceWidget')||$('#vmUserAttendanceWidget'); if(!mount) return; let user=currentUser(); if(!user){mount.innerHTML='';return} let emp=findEmp(user), rows=get('attendance',[]).filter(x=>x.employeeId===emp.id), todayRow=rows.find(x=>x.date===today())||{}; let bio=get('biometricCredentials',[]).find(x=>x.userId===user.id&&x.status==='active'); let loc=get('employeeLocations',[]).find(x=>x.userId===user.id&&x.status==='active'); mount.innerHTML=`<div class="vm-portal-card"><div class="vm-portal-title"><i class="fas fa-fingerprint"></i> الحضور والانصراف بالبصمة والموقع</div><p class="vm-note">يتم استخدام WebAuthn/Passkeys عند دعم الجهاز. لا يتم حفظ صورة البصمة، بل مفتاح تحقق آمن فقط.</p><div class="vm-kpi-grid"><div class="vm-kpi"><b>${todayRow.checkIn||'—'}</b><span>آخر حضور</span></div><div class="vm-kpi"><b>${todayRow.checkOut||'—'}</b><span>آخر انصراف</span></div><div class="vm-kpi"><b>${todayRow.totalHours||0}</b><span>ساعات اليوم</span></div><div class="vm-kpi"><b>${todayRow.attendanceStatus||'خارج الدوام'}</b><span>حالة الدوام</span></div></div><div class="vm-actions"><button class="vm-btn vm-btn-gold" onclick="VMGeoBio.registerMyPasskey()"><i class="fas fa-fingerprint"></i>${bio?'إعادة طلب تفعيل البصمة':'تفعيل البصمة / Face ID'}</button><button class="vm-btn vm-btn-soft" onclick="VMGeoBio.saveMyLocation()"><i class="fas fa-location-crosshairs"></i>${loc?'طلب تغيير الموقع':'حفظ موقعي الأساسي'}</button><button class="vm-btn vm-btn-primary" onclick="VMGeoBio.checkIn()"><i class="fas fa-right-to-bracket"></i>تسجيل حضور</button><button class="vm-btn vm-btn-primary" onclick="VMGeoBio.checkOut()"><i class="fas fa-right-from-bracket"></i>تسجيل انصراف</button></div><div style="margin-top:12px"><span class="vm-status ${bio?'ok':'warn'}">${bio?'البصمة مفعلة':'البصمة غير مفعلة'}</span> <span class="vm-status ${loc?'ok':'warn'}">${loc?'الموقع الأساسي محفوظ':'الموقع غير محفوظ'}</span> <span class="vm-status ok">${todayRow.verificationMethod||'PIN احتياطي متاح'}</span></div><div id="portalMiniMap" class="vm-map" style="height:260px;margin-top:14px"></div></div>`; setTimeout(()=>drawPortalMap(loc,todayRow),100);}
function drawPortalMap(loc,row){let el=$('#portalMiniMap'); if(!el||!window.L) return; el.innerHTML=''; let lat=(loc&&loc.lat)||(row.checkInLocation&&row.checkInLocation.lat)||21.543, lng=(loc&&loc.lng)||(row.checkInLocation&&row.checkInLocation.lng)||39.172; let map=L.map(el).setView([lat,lng],13); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'OSM'}).addTo(map); if(loc) L.marker([loc.lat,loc.lng]).addTo(map).bindPopup('الموقع الأساسي'); if(row.checkInLocation) L.marker([row.checkInLocation.lat,row.checkInLocation.lng]).addTo(map).bindPopup('موقع الحضور'); let b=getBranch(); if(b.lat&&b.lng){L.marker([b.lat,b.lng]).addTo(map).bindPopup(b.name||'موقع الشركة'); L.circle([b.lat,b.lng],{radius:+b.radius||250}).addTo(map)}}
window.VMGeoBio={registerMyPasskey:async()=>{let u=currentUser(); if(!u)return toast('سجل الدخول أولًا'); let exists=get('biometricCredentials',[]).find(x=>x.userId===u.id); if(exists){createRequest(u,'biometric','طلب إعادة تفعيل البصمة أو تغيير الجهاز',deviceInfo()); return toast('تم إرسال طلب إعادة تفعيل البصمة للأدمن');} try{await registerPasskey(u); renderPortalWidget(); toast('تم تفعيل البصمة بنجاح')}catch(e){toast(e.message||'تعذر تفعيل البصمة')}},saveMyLocation:async()=>{let u=currentUser(); if(!u)return toast('سجل الدخول أولًا'); let old=get('employeeLocations',[]).find(x=>x.userId===u.id&&x.status==='active'); let gps=await getGPS(); if(!gps)return toast('لم يتم السماح بالموقع'); if(old){createRequest(u,'location','طلب تغيير الموقع الأساسي',gps); return toast('تم إرسال طلب تغيير الموقع للأدمن')} await ensureBaseLocation(u); renderPortalWidget(); toast('تم حفظ الموقع الأساسي')},checkIn:()=>punch('in'),checkOut:()=>punch('out'),render:renderPortalWidget};
function adminRows(){let u=users(), creds=get('biometricCredentials',[]); let tbody=$('#biometricAdminRows'); if(tbody) tbody.innerHTML=u.map(x=>{let c=creds.find(y=>y.userId===x.id);return `<tr><td>${x.fullName||x.name||x.username||'—'}</td><td>${x.role||'user'}</td><td><span class="badge ${c&&c.status==='active'?'badge-progress':'badge-review'}">${c?c.status:'غير مفعلة'}</span></td><td>${c?(c.deviceInfo||{}).platform||'محفوظ':'—'}</td><td>${c?new Date(c.createdAt).toLocaleString('ar-SA'):'—'}</td><td><button class="btn btn-sm btn-warning" onclick="VMGeoBioAdmin.disableBio('${x.id}')">تعطيل</button><button class="btn btn-sm btn-danger" onclick="VMGeoBioAdmin.deleteBio('${x.id}')">حذف</button><button class="btn btn-sm btn-success" onclick="VMGeoBioAdmin.approveBio('${x.id}')">السماح بإعادة التفعيل</button></td></tr>`}).join('')||'<tr><td colspan="6">لا يوجد مستخدمون</td></tr>'; let bc=$('#bioCredCount'); if(bc) bc.textContent=creds.filter(x=>x.status==='active').length; let br=$('#bioReqCount'); if(br) br.textContent=get('reactivationRequests',[]).filter(x=>x.status==='pending'&&x.type==='biometric').length; let bd=$('#bioDisabledCount'); if(bd) bd.textContent=creds.filter(x=>x.status==='disabled').length; let rb=$('#reactivationBadge'); if(rb) rb.textContent=get('reactivationRequests',[]).filter(x=>x.status==='pending').length;}
function renderBranches(){let tbody=$('#branchRows'), arr=get('branches',[]); if(tbody) tbody.innerHTML=arr.map(b=>`<tr><td>${b.name}</td><td>${b.lat}, ${b.lng}</td><td>${b.radius} متر</td><td>${b.allowOutside?'مسموح':'ممنوع'}</td><td><button class="btn btn-sm btn-danger" onclick="VMGeoBioAdmin.deleteBranch('${b.id}')">حذف</button></td></tr>`).join('')||'<tr><td colspan="5">لا توجد فروع مسجلة</td></tr>'; drawAdminBranchMap();}
function renderRequests(type='all'){let tbody=$('#reactivationRows'), arr=get('reactivationRequests',[]).filter(r=>type==='all'||r.type===type); if(tbody) tbody.innerHTML=arr.map(r=>`<tr><td>${r.name||'—'}</td><td>${r.type==='biometric'?'بصمة':r.type==='location'?'موقع':'جهاز'}</td><td>${new Date(r.createdAt).toLocaleString('ar-SA')}</td><td><small>${summ(r.oldData)}</small></td><td><small>${summ(r.newData)}</small></td><td>${r.reason||'—'}</td><td><span class="badge ${r.status==='approved'?'badge-progress':r.status==='rejected'?'badge-rejected':'badge-review'}">${r.status}</span></td><td><button class="btn btn-sm btn-success" onclick="VMGeoBioAdmin.setReq('${r.id}','approved')">قبول</button><button class="btn btn-sm btn-danger" onclick="VMGeoBioAdmin.setReq('${r.id}','rejected')">رفض</button><button class="btn btn-sm btn-warning" onclick="VMGeoBioAdmin.setReq('${r.id}','hold')">تعليق</button></td></tr>`).join('')||'<tr><td colspan="8">لا توجد طلبات</td></tr>'; adminRows();}
function summ(o){if(!o)return '—'; if(o.lat)return `${(+o.lat).toFixed(5)}, ${(+(o.lng||0)).toFixed(5)}`; if(o.ua)return (o.platform||'جهاز')+' '+(o.language||''); if(o.credentialId)return 'مفتاح WebAuthn محفوظ'; return 'بيانات محفوظة'}
function drawAdminBranchMap(){let el=$('#adminBranchMap'); if(!el||!window.L)return; el.innerHTML=''; let arr=get('branches',[]), first=arr[0]||{lat:21.543,lng:39.172,radius:250,name:'موقع افتراضي'}; let map=L.map(el).setView([+first.lat,+first.lng],12); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'OSM'}).addTo(map); arr.forEach(b=>{L.marker([+b.lat,+b.lng]).addTo(map).bindPopup(b.name); L.circle([+b.lat,+b.lng],{radius:+b.radius||250}).addTo(map)}); map.on('click',e=>{let lat=$('#branchLat'),lng=$('#branchLng'); if(lat)lat.value=e.latlng.lat.toFixed(6); if(lng)lng.value=e.latlng.lng.toFixed(6);});}
function drawEmployeeMap(){let el=$('#employeeLiveMap'); if(!el||!window.L)return; el.innerHTML=''; let locs=get('employeeLocations',[]), at=get('attendance',[]), branches=get('branches',[]); let center=branches[0]||locs[0]||{lat:21.543,lng:39.172}; let map=L.map(el).setView([+center.lat,+center.lng],11); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'OSM'}).addTo(map); branches.forEach(b=>{L.marker([+b.lat,+b.lng]).addTo(map).bindPopup('فرع: '+b.name); L.circle([+b.lat,+b.lng],{radius:+b.radius||250}).addTo(map)}); locs.forEach(l=>L.marker([+l.lat,+l.lng]).addTo(map).bindPopup('موقع أساسي')); at.filter(r=>r.checkInLocation).slice(-50).forEach(r=>L.marker([+r.checkInLocation.lat,+r.checkInLocation.lng]).addTo(map).bindPopup('حضور: '+r.employeeName)); let tbody=$('#employeeLocationRows'); if(tbody){let emps=get('employees',[]); tbody.innerHTML=emps.map(e=>{let l=locs.find(x=>x.employeeId===e.id), last=at.filter(x=>x.employeeId===e.id).pop()||{}; return `<tr><td>${e.fullName}</td><td>${l?`${(+l.lat).toFixed(5)}, ${(+l.lng).toFixed(5)}`:'غير محفوظ'}</td><td>${last.checkIn||'—'}</td><td>${last.checkOut||'—'}</td><td>${e.allowOutside?'مسموح':'ممنوع'}</td><td><button class="btn btn-sm btn-outline" onclick="VMGeoBioAdmin.toggleOutside('${e.id}')">تبديل السماح</button></td></tr>`}).join('')||'<tr><td colspan="6">لا يوجد موظفون</td></tr>'}}
window.VMGeoBioAdmin={render:()=>{adminRows();renderBranches();renderRequests();drawEmployeeMap()},saveBranch:()=>{let arr=get('branches',[]);let item={id:uid(),name:$('#branchName')?.value||'فرع',lat:$('#branchLat')?.value,lng:$('#branchLng')?.value,radius:+($('#branchRadius')?.value||250),allowOutside:($('#branchAllowOutside')?.value==='true'),createdAt:now()}; if(!item.lat||!item.lng)return toast('حدد خط العرض والطول'); arr.push(item); set('branches',arr); set('attendanceSettings',{companyLat:item.lat,companyLng:item.lng,radius:item.radius,allowOutside:item.allowOutside}); log('create','branches','إضافة فرع',null,item); renderBranches();},useCurrentCompanyLocation:async()=>{let g=await getGPS(); if(!g)return toast('لم يتم السماح بالموقع'); $('#branchLat').value=g.lat.toFixed(6); $('#branchLng').value=g.lng.toFixed(6);},deleteBranch:(id)=>{if(!confirm('حذف الفرع؟'))return; let arr=get('branches',[]); let old=arr.find(x=>x.id===id); set('branches',arr.filter(x=>x.id!==id)); log('delete','branches','حذف فرع',old,null); renderBranches();},disableBio:(uidv)=>{let arr=get('biometricCredentials',[]); arr.forEach(x=>{if(x.userId===uidv)x.status='disabled'}); set('biometricCredentials',arr); adminRows();},deleteBio:(uidv)=>{if(!confirm('حذف مفتاح البصمة؟'))return; set('biometricCredentials',get('biometricCredentials',[]).filter(x=>x.userId!==uidv)); adminRows();},approveBio:(uidv)=>{notify(uidv,'biometric','تم السماح بإعادة تفعيل البصمة','يمكنك الآن تفعيل بصمة جديدة من صفحة المستخدم'); toast('تم إرسال السماح للمستخدم');},renderRequests,setReq:(id,status)=>{let arr=get('reactivationRequests',[]), r=arr.find(x=>x.id===id); if(r){r.status=status;r.approvedBy='admin';r.updatedAt=now(); if(status==='approved'&&r.type==='location'&&r.newData&&r.newData.lat){let locs=get('employeeLocations',[]); locs.forEach(l=>{if(l.userId===r.userId)l.status='old'}); locs.push({id:uid(),userId:r.userId,employeeId:r.employeeId,lat:r.newData.lat,lng:r.newData.lng,accuracy:r.newData.accuracy,address:'تم اعتماده من الأدمن',status:'active',createdAt:now()}); set('employeeLocations',locs)} if(status==='approved'&&r.type==='biometric'){set('biometricCredentials',get('biometricCredentials',[]).filter(x=>x.userId!==r.userId));} set('reactivationRequests',arr); notify(r.userId,'reactivation',status==='approved'?'تم قبول طلبك':'تم تحديث طلبك','حالة طلب إعادة التفعيل: '+status); log('update','reactivation','تحديث طلب إعادة التفعيل',null,r);} renderRequests();},toggleOutside:(id)=>{let e=get('employees',[]); let emp=e.find(x=>x.id===id); if(emp){emp.allowOutside=!emp.allowOutside;set('employees',e);drawEmployeeMap();}},};
function addPortalMounts(){ if((location.pathname.includes('user-portal')||location.pathname.includes('employee-portal')||location.pathname.includes('employee.html')) && !$('#vmEmployeeAttendanceWidget') && !$('#vmUserAttendanceWidget')){let main=$('main')||$('.portal')||$('.container')||document.body; let div=document.createElement('div'); div.id='vmEmployeeAttendanceWidget'; main.prepend(div); renderPortalWidget();}}
function addSeparatedCards(){let p=$('#p-dashboard .dash-content')||$('#p-dashboard'); if(!p||$('#vmSeparatedCards'))return; let box=document.createElement('div');box.id='vmSeparatedCards'; box.className='card'; box.innerHTML='<div class="card-title"><i class="fas fa-sitemap"></i> صفحات إدارية منفصلة</div><div class="vm-separate-grid"><a class="vm-section-link" href="admin-employees.html"><i class="fas fa-user-tie"></i><b>إدارة الموظفين</b><span>بيانات الموظفين، الربط بحساب المستخدم، الحالة، القسم والراتب.</span></a><a class="vm-section-link" href="admin-attendance.html"><i class="fas fa-calendar-check"></i><b>الحضور والانصراف</b><span>تسجيل، اعتماد، تعديل، تصدير، وبصمة/GPS.</span></a><a class="vm-section-link" href="admin-locations.html"><i class="fas fa-map"></i><b>إدارة المواقع والخرائط</b><span>الفروع، نطاق الدوام، ومواقع الموظفين.</span></a><a class="vm-section-link" href="admin-permissions.html"><i class="fas fa-key"></i><b>إدارة الصلاحيات</b><span>فتح وإغلاق الصلاحيات حسب المستخدم.</span></a></div>'; p.appendChild(box);}
document.addEventListener('DOMContentLoaded',()=>{addPortalMounts();addSeparatedCards(); if(location.pathname.includes('admin-dashboard')) setTimeout(()=>VMGeoBioAdmin.render(),500);});
setInterval(()=>{if(location.pathname.includes('admin-dashboard')) adminRows(); renderPortalWidget();},5000);
})();
