services:
  - type: web
    name: vision-media-auto-social-api
    env: node
    plan: starter
    rootDir: apps/api
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
