
// VISION MEDIA Legal System + Admin CMS + Native Notifications Patch
(function(){
'use strict';
var POLICIES = {
  'privacy.html':'سياسة الخصوصية','terms.html':'الشروط والأحكام','refund.html':'سياسة الاسترجاع والاستبدال','digital-services-policy.html':'سياسة الخدمات الرقمية','customer-policy.html':'سياسة العملاء','payment-policy.html':'سياسة الدفع','advertising-policy.html':'سياسة الإعلانات والتسويق','ai-policy.html':'سياسة الذكاء الاصطناعي','notifications-policy.html':'سياسة الإشعارات','security-policy.html':'سياسة الأمان والحماية','faq.html':'الأسئلة الشائعة','intellectual-property.html':'حقوق الملكية الفكرية'
};
function $(s,r){return (r||document).querySelector(s)} function $all(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s))}
function read(k,d){try{var v=localStorage.getItem(k);return v?JSON.parse(v):d}catch(e){return d}} function write(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
function toast(m,type){ if(window.VM&&VM.notify){VM.notify(m,type||'success');return} var t=document.createElement('div');t.textContent=m;t.style.cssText='position:fixed;top:18px;left:50%;transform:translateX(-50%);z-index:2147483647;background:'+(type==='error'?'#b91c1c':'#07111e')+';color:white;padding:13px 18px;border-radius:14px;font-family:Tahoma;box-shadow:0 18px 50px rgba(0,0,0,.25)';document.body.appendChild(t);setTimeout(function(){t.remove()},2800)}
function isAdmin(){var s=read('vm_admin_session',null),u=read('vm_currentUser',null);return !!((s&&s.role==='admin')||(u&&(u.role==='admin'||String(u.email||'').toLowerCase()==='admin@visionmedia.local')))}
function setAdmin(){write('vm_admin_session',{username:'admin',role:'admin',loggedAt:new Date().toISOString()});write('vm_currentUser',{name:'المدير العام',email:'admin@visionmedia.local',role:'admin'});}
function fixAdmin(){ if(/admin-dashboard\.html/.test(location.pathname)&&!isAdmin()) location.href='admin.html'; if(/admin\.html$|\/admin\/?$/.test(location.pathname)){var f=$('#f'),u=$('#u'),p=$('#pw'),err=$('#err'); if(f&&u&&p){f.onsubmit=function(e){e.preventDefault(); if(u.value.trim()==='admin'&&p.value.trim()==='0543944248'){setAdmin(); location.href='admin-dashboard.html'}else{if(err){err.style.display='block';err.textContent='بيانات الدخول غير صحيحة'} toast('بيانات الأدمن غير صحيحة','error')}}}}}
function triple(){var targets=$all('.nav-logo,.sidebar-logo,.logo,.footer-brand h3,[class*=logo]'); targets.forEach(function(el){var c=0,t; el.style.cursor='pointer'; el.addEventListener('click',function(e){c++; clearTimeout(t); t=setTimeout(function(){c=0},800); if(c>=3){e.preventDefault(); e.stopPropagation(); c=0; location.href='admin.html'}},true)})}
async function askNotification(){ if(!('Notification' in window)){toast('المتصفح لا يدعم الإشعارات','error');return} var res=await Notification.requestPermission(); write('vm_notification_permission',{status:res,at:new Date().toISOString()}); if(res==='granted'){toast('تم السماح بالإشعارات من المتصفح','success'); try{ if('serviceWorker' in navigator) await navigator.serviceWorker.register('/firebase-messaging-sw.js'); }catch(e){} } else if(res==='denied') toast('تم رفض الإشعارات من المتصفح','error'); else toast('تم تأجيل الإشعارات','info'); }
function notificationBox(){ if(!('Notification' in window)) return; if(Notification.permission==='granted'||Notification.permission==='denied'||read('vm_notification_permission',null)) return; var b=document.createElement('div'); b.className='vm-notification-native'; b.innerHTML='<div class="ico"><i class="fa-solid fa-bell"></i></div><div style="flex:1"><b>السماح بإشعارات VISION MEDIA</b><span>اضغط سماح ليظهر طلب المتصفح الأصلي مثل جوجل كروم.</span></div><button class="allow">سماح</button><button class="later">لاحقًا</button>'; document.body.appendChild(b); $('.allow',b).onclick=askNotification; $('.later',b).onclick=function(){write('vm_notification_permission',{status:'later',at:new Date().toISOString()});b.remove()}; }
function hookButtons(){ $all('a,button').forEach(function(el){var txt=(el.textContent||'')+(el.title||''); if(txt.indexOf('إشعار')>-1||txt.indexOf('تنبيه')>-1){el.addEventListener('click',function(e){e.preventDefault(); askNotification()},true)}})}
function injectFooterLegal(){
  var footer=$('footer.footer')||$('footer'); if(!footer) return;
  $all('.vm-footer-legal',footer).forEach(function(x){x.remove()});
  var linksHtml=Object.keys(POLICIES).map(function(k){return '<li><a href="'+k+'">'+POLICIES[k]+'</a></li>'}).join('');
  var legalBox=null;
  $all('.footer-links',footer).forEach(function(box){var h=$('h4',box); if(h && /قانوني|سياسات|الشروط/.test(h.textContent||'')) legalBox=box;});
  if(!legalBox){
    var grid=$('.footer-grid',footer); if(!grid) return;
    legalBox=document.createElement('div'); legalBox.className='footer-links vm-legal-links-box'; legalBox.innerHTML='<h4>السياسات والشروط</h4><ul></ul>'; grid.appendChild(legalBox);
  }
  var ul=$('ul',legalBox); if(!ul){ul=document.createElement('ul'); legalBox.appendChild(ul)}
  ul.innerHTML=linksHtml;
  legalBox.setAttribute('data-vm-legal-box','1');
}
function injectAdminPolicies(){ if(!/admin-dashboard\.html/.test(location.pathname)) return; var nav=$('.dash-sidebar nav'); if(nav&&!document.querySelector('[data-policy-nav]')){var a=document.createElement('a');a.className='dash-nav-link';a.setAttribute('data-policy-nav','1');a.innerHTML='<i class="fas fa-scale-balanced"></i> السياسات والشروط';a.onclick=function(){ if(window.showPanel) showPanel('p-policies',a); }; nav.appendChild(a)} var main=$('.dash-content')||$('.dash-main')||document.body; if(!$('#p-policies')){var p=document.createElement('section');p.className='panel';p.id='p-policies';p.innerHTML='<div class="page-title">إدارة السياسات والشروط</div><p class="page-sub">تعديل، نشر، إخفاء، ترتيب ومعاينة صفحات السياسات القانونية.</p><div class="vm-policy-admin-card"><div class="form-row"><div class="form-group"><label class="form-label">اختر الصفحة</label><select id="policySelect" class="form-control"></select></div><div class="form-group"><label class="form-label">حالة النشر</label><select id="policyVisible" class="form-control"><option value="true">منشورة</option><option value="false">مخفية</option></select></div></div><div class="form-group"><label class="form-label">عنوان الصفحة</label><input id="policyTitle" class="form-control"></div><div class="form-group"><label class="form-label">النص</label><textarea id="policyContent" class="form-control" style="min-height:300px"></textarea></div><button class="btn btn-primary" id="savePolicyBtn"><i class="fas fa-save"></i> حفظ السياسة</button> <button class="btn btn-outline" id="previewPolicyBtn"><i class="fas fa-eye"></i> معاينة</button></div><div id="policyAdminList"></div>'; main.appendChild(p)} var sel=$('#policySelect'); if(sel&&!sel.options.length){sel.innerHTML=Object.keys(POLICIES).map(function(k){return '<option value="'+k+'">'+POLICIES[k]+'</option>'}).join(''); sel.onchange=loadPolicyAdmin; $('#savePolicyBtn').onclick=savePolicyAdmin; $('#previewPolicyBtn').onclick=function(){window.open(sel.value,'_blank')}; loadPolicyAdmin();} renderPolicyList(); }
function loadPolicyAdmin(){var k=$('#policySelect').value; var d=read('vm_policy_'+k,{title:POLICIES[k],content:'',visible:true}); $('#policyTitle').value=d.title||POLICIES[k]; $('#policyVisible').value=String(d.visible!==false); $('#policyContent').value=d.content||'يمكن تعديل نص هذه السياسة من هنا. الصفحة الأصلية موجودة بالفعل داخل الموقع.';}
function savePolicyAdmin(){var k=$('#policySelect').value; write('vm_policy_'+k,{title:$('#policyTitle').value,content:$('#policyContent').value,visible:$('#policyVisible').value==='true',updatedAt:new Date().toISOString()}); toast('تم حفظ السياسة بنجاح','success'); renderPolicyList(); try{ if(window.VMFirebaseReady) VMFirebaseReady.then(function(fb){ if(fb&&fb.online) fb.db.collection('policies').doc(k.replace('.html','')).set(read('vm_policy_'+k,{}),{merge:true});}); }catch(e){} }
function renderPolicyList(){var el=$('#policyAdminList'); if(!el)return; el.innerHTML=Object.keys(POLICIES).map(function(k){var d=read('vm_policy_'+k,{visible:true});return '<div class="vm-policy-admin-card" style="display:flex;justify-content:space-between;gap:12px;align-items:center"><b>'+POLICIES[k]+'</b><span>'+(d.visible===false?'مخفية':'منشورة')+'</span><a class="btn btn-sm btn-outline" href="'+k+'" target="_blank">فتح</a></div>'}).join('');}
function addSEO(){ if(document.querySelector('script[type="application/ld+json"][data-vm-schema]'))return; var s=document.createElement('script');s.type='application/ld+json';s.setAttribute('data-vm-schema','1');s.textContent=JSON.stringify({'@context':'https://schema.org','@type':'Organization','name':'VISION MEDIA','url':location.origin,'contactPoint':{'@type':'ContactPoint','telephone':'+966543944248','contactType':'customer service'},'sameAs':['https://www.instagram.com/advertisement_portal.46','https://www.facebook.com/share/1DszbP1nTB/','https://www.tiktok.com/@waelelsayd3']});document.head.appendChild(s)}
document.addEventListener('DOMContentLoaded',function(){fixAdmin();triple();// notificationBox(); تم التعطيل لصالح طلب المتصفح الأصلي مرة واحدةhookButtons();injectFooterLegal();injectAdminPolicies();addSEO();});
})();
